version: "3.7"
services:
  spark-master:
    image: spydernaz/spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./docker-volumes/apps:/opt/spark-apps
       - ./docker-volumes/data:/opt/spark-data
       - ./docker-volumes/output:/opt/spark-output
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: spydernaz/spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=256m
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
       - ./docker-volumes/apps:/opt/spark-apps
       - ./docker-volumes/data:/opt/spark-data
       - ./docker-volumes/output:/opt/spark-output
